# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: caee8d70c221a06329be790556fe4839e0ef3d7bc0c7d45aad8ae1bb0209bba18ef91d92ee0375bf7e5874f60b9cd3d2cc4a24aa933ef60473214d99d0d4cf98

test:
  secret_key_base: 8900f2637695d9df5fda249a8945ae142dea8451104a96f0a9e6b3d5feca814bad0ccfb914973e650f305170236255d52dfd91bd2a17275eb95ef6f85ddd242c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
